#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADZONE 10
#define SPEEDLIMIT 100
#define ANGULE_TOLERANCE 10

float standard_angule(float teta);
float define_angule(int x, int y);
void turn_left(float gyroscope, float controler);
void turn_right(float gyroscope, float controler);
void turn_robot(float gyroscope, float controler);
void drive();

task main()
{
	SensorType[in8] = sensorNone;
  wait1Msec(1000);
  SensorType[in8] = sensorGyro;
  wait1Msec(2000);
	while(true){
		drive();
	}
}

void drive(){
	int vel_H;
	int vel_V;
	int vel_right;
//	int vel_left;
	float gyroscope_angule;
	float controler_angule;
	vel_H=vexRT[Ch4];
	vel_V=vexRT[Ch3];

	if(abs(vel_H)>DEADZONE && abs(vel_V)>DEADZONE){
		gyroscope_angule=SensorValue[in8]/10.0;
		gyroscope_angule=standard_angule(gyroscope_angule);
		controler_angule=define_angule(vel_H, vel_V);

		if(abs(gyroscope_angule-controler_angule)>ANGULE_TOLERANCE) turn_robot(gyroscope_angule,controler_angule);
		else{
			vel_right=sqrt(vel_H*vel_H+vel_V*vel_V);        //define velocidade
			if (vel_right>SPEEDLIMIT) vel_right=SPEEDLIMIT; //ninguem quer queimar o motor
			motor[right]=vel_right;                         //seta velocidade no motor
			motor[left]=vel_right;
		}
	}

}

float define_angule(int x, int y){
	float teta;
	float divisor;
	if(x==0) divisor=0.0000001;
	teta=360.0/(2*PI)*atan((float)y/divisor);
	if(x<0)teta+=180;
	if(teta<0)teta+=360; //eu quero meu range de 0 a 360
	return teta;
}

float standard_angule(float teta){
	while(teta<0) teta+=360;
	while(teta>=360) teta-=360;
	return teta;
}

void turn_robot(float gyroscope, float controler){
	float diferenca;
	diferenca = gyroscope-controler;
	if(standard_angule(gyroscope-controler)<180) turn_right(gyroscope, controler);
	else turn_left(gyroscope, controler);
}

void turn_right(float gyroscope, float controler){
  motor[right] = 30;
  motor[left] = -30;
}

void turn_left(float gyroscope, float controler){
  motor[right] = -30;
  motor[left] = 30;
}
