#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define DEADZONE 10
#define SPEEDLIMIT 100

void drive();

task main()
{
	while(true){
		drive();
	}
}

void drive(){
	int vel_H;
	int vel_V;
	int vel_right;
	int vel_left;
	vel_H=vexRT[Ch4];
	vel_V=vexRT[Ch3];

	if(vel_H>-DEADZONE && vel_H<DEADZONE) vel_H=0;  //zona morta, mano
	if(vel_V>-DEADZONE && vel_V<DEADZONE) vel_V=0;  //zona morta, mano

	vel_right=vel_H-vel_V; //define velocidade
	if (vel_right>SPEEDLIMIT) vel_right=SPEEDLIMIT; //ninguem quer queimar o motor
	else if (vel_right<-SPEEDLIMIT) vel_right=-SPEEDLIMIT; //definitivamente nao eh legal queimar o motor
	motor[right]=vel_right; //seta velocidade no motor

	vel_left=vel_H+vel_V;
	if (vel_left>SPEEDLIMIT) vel_left=SPEEDLIMIT;
	else if (vel_left<-SPEEDLIMIT) vel_left=-SPEEDLIMIT;
	motor[left] =vel_left;
}
