#pragma config(Motor,  port1,           rightCenter,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           intake2ndStage, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shooterTop,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooterMid,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           shooterBot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake1stStage, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftCenter,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SATURATION_UP 120
#define SATURATION_DOWN 0
#define DEADZONE 10
#define MOTOR_DEADZONE 20

int shootSpeed = 0;

void drive();
void intake1();
void intake2();
void shooter();

/* User Control */
task main()
{
	while(true)
	{
		drive();
		intake1();
		intake2();
		shooter();
	}
}



void drive()
{
	if(vexRT[Ch2]>DEADZONE || vexRT[Ch2]<-DEADZONE)
	{
		motor[leftDrive]=vexRT[Ch2];
		motor[leftCenter]=vexRT[Ch2];
	}
	else
	{
		motor[leftDrive]=0;
		motor[leftCenter]=0;
	}
	if(vexRT[Ch3]>DEADZONE || vexRT[Ch3]<-DEADZONE)
	{
		motor[rightDrive]=vexRT[Ch3];
		motor[rightCenter]=vexRT[Ch3];
	}
	else
	{
		motor[rightDrive]=0;
		motor[rightCenter]=0;
	}
}

void intake1()
{
	 motor[intake1stStage] = vexRT[Btn5U] ? 127 : vexRT[Btn5D] ? -127 : 0;
}

void intake2()
{
	 motor[intake2ndStage] = vexRT[Btn6U] ? 127 : vexRT[Btn6D] ? -127 : 0;
}

void shooter()
{
	shootSpeed = vexRT[Btn8R] ? 100 : vexRT[Btn8D] ? 0 : shootSpeed;

	motor[shooterTop] = shootSpeed;
	motor[shooterMid] = shootSpeed;
	motor[shooterBot] = shootSpeed;

}
