#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  barSensor,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftBumper,     sensorTouch)
#pragma config(Sensor, dgtl4,  rightBumper,    sensorTouch)
#pragma config(Sensor, dgtl5,  intakeSensor,   sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  leftDriveEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl11, shooterEnc,     sensorQuadEncoder)
#pragma config(Motor,  port1,           rightCenterDrive, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           shooterTop,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intake2ndStage, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooterMid,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftRelease,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intake1stStage, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shooterBot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftCenterDrive, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"
#include "phenix_PID.h"
#include "xytheta.h"
#include "phenix_UART.h"
#include "DriverCntrl.h"
#include "AutonCntrl.h"

/* Autonomous */
void pre_auton()
{
}

task autonomous()
{
	//clear sensors
	clearAll(actOnSensors);
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);


	//start x, y, theta system
	startTask(UpdatePosition);

	//PID autonomous beginning
	shooter_MotorInit(&flyWheel, shooterTop, shooterMid, shooterBot, shooterEnc);
	startTask(autonShooterControl);
	bigBot.autonTargetSpeed = 0;

	//start pixy communication
	configureSerial();
	startTask(UARTReceive);

	//Initial positioning
	//setBallPositions();
	InitialPositioning();
	while(true)
	{
		Turn(90);
		Turn(180);
		Turn(270);
		Turn(0);
	}
	while(true)
	{
		wait1Msec(100);
		while(closestBall.sig == 'N'){}
		while(bigBot.ballCount < 1)
		{
			TrackBall();
			Stop();
			intakeSequence();
		}
		set1stIntake(-127);
		moveToLocation(24 * 2, 24 * 2);
		moveToLocation(24 * 3, 24 * 3);// first is 84 91 drift is fairly prevelant, will account for
		bigBot.autonTargetSpeed = 85; //check for gyro drift before running auton
		Turn(45);
		Unload();
		moveToLocation(20, 20);
	}
	//	moveToLocation(rand() % 80 + 20, rand() % 80 + 20);
	//	Stop();
	//	wait1Msec(100);
	//	moveToLocation(0, 0);
	//	Stop();
	//	wait1Msec(100);
	//}
	//move to the center of the field
	//moveToLocation(2*60.96-30, 3*60.96-30);

	//Bot is initially searching for balls
	//bigBot.state = Inspection;

}

/* User Control */
task usercontrol()
{
	shooter_MotorInit(&flyWheel, shooterTop, shooterMid, shooterBot, shooterEnc);

	while(true)
	{
		drive();
		cntrl_intake1();
		cntrl_intake2();
		shooter(&flyWheel);
		lock_move();
	}
}
