#pragma config(Motor,  port1,           back,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           mid,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          front,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void CAM ()
{
	int power = vexRT[Btn6U] ? 127 : vexRT[Btn6D] ? -127 : 0;

	motor[front] = power;
	motor[mid] = power;
	motor[back] = power;

}

task main()
{
	while(true)
	{
		CAM();
	}
}
