                                                                                                                                                                                                                                                                                                   #pragma config(Motor,  port1,           fly1,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           shoot3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           shoot1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftMotor2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           shoot2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          fly2,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
int button8U;
int button6U;
int button8R;
int button6D;

/////////////////////////////////////////

void drive()
{

	motor[leftMotor1]=vexRT[Ch3];
	motor[leftMotor2]=vexRT[Ch3];

	motor[rightMotor1]=vexRT[Ch2];
	motor[rightMotor2]=vexRT[Ch2];

}

//////////////////////////////////////////

void punch()
{
	if(vexRT[Btn8D])
	{
		motor[shoot1] = 127;
		motor[shoot2] = 127;
		motor[shoot3] = 127;
	}
	else
	{
		motor[shoot1] = 0;
		motor[shoot2] = 0;
		motor[shoot3] = 0;
	}
}

//////////////////////////////////////////

void inTaker()
{
	button6U=vexRT[Btn6U];
	button6D=vexRT[Btn6D];



	if(button6U==1)
	{

		motor[intake]=127;

	}
	else if(button6D==1)
	{
		motor[intake]=-127;

	}
	else
	{
		motor[intake]=0;


	}

}
/////////////////////////////////////////////

void flyShoot()
{

	button8U=vexRT[Btn8U];
	button8R=vexRT[Btn8R];

	if(button8U==1)
	{
		motor[fly1]=105;
		motor[fly2]=105;

	}
	else if(button8R ==1)
	{
		motor[fly1]=0;
		motor[fly2]=0;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		flyShoot();
		inTaker();
		drive();
		punch();

	}
}
