#pragma config(Motor,  port1,           leftBack,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftCenter,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftShooter,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightShooter,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCenter,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADZONE 15
#define MAXSPEED 120
#define MINSPEED 0

int shootSpeed = MINSPEED;
int shootMode = 0;
int DriveMode = -1;
bool isSwitchingModes = false;
bool isSwitchingSpeeds = false;

//////////////////////////////////////////////////////////////////////

void drive()
{

	if(vexRT[Btn7U] && !isSwitchingModes)//change modes
	{

			DriveMode = -DriveMode;
			isSwitchingModes = true;
	}
	else if(vexRT[Btn7U] == 0)
	{
			isSwitchingModes = false;
	}

	if(DriveMode == 1) //arcade drive
	{
		int y = abs(vexRT[Ch3]) < DEADZONE ? 0 : vexRT[Ch3];
		int x = abs(vexRT[Ch1]) < DEADZONE ? 0 : vexRT[Ch1];

		motor[leftBack] = y + x;
		motor[leftCenter] = y + x;
		motor[leftFront] = y + x;

		motor[rightBack] = y - x;
		motor[rightCenter] = y - x;
		motor[rightFront] = y - x;


	}
	else if(DriveMode == -1) //tank drive
	{
		int rightPower = abs(vexRT[Ch2]) < DEADZONE ? 0 : vexRT[Ch2];
		int leftPower  = abs(vexRT[Ch3]) < DEADZONE ? 0 : vexRT[Ch3];

		motor[leftBack] = leftPower;
		motor[leftCenter] = leftPower;
		motor[leftFront] = leftPower;

		motor[rightBack] = rightPower;
		motor[rightCenter] = rightPower;
		motor[rightFront] = rightPower;
	}
}

////////////////////////////////////////////////////////////////////////////////////

void ctrl_intake()
{
	int power_in = vexRT[Btn5U] ? 127 : vexRT[Btn5D] ? -127 : 0;

	motor[intake] = power_in;

}

////////////////////////////////////////////////////////////////////////////////////

void ctrl_shooter()
{
	if(vexRT[Btn6D] == 1)
	{
		shootMode = 0;
	}
	else if(vexRT[Btn8U] == 1)
	{
		shootMode = 1;
	}
	else if(vexRT[Btn8D] == 1)
	{
		shootMode = 2;
	}

	shootSpeed = shootMode == 0 ? 0 : shootMode == 1 ? 80 : shootMode == 2 ? 50 : 0;

	motor[leftShooter] = shootSpeed;
	motor[rightShooter] = shootSpeed;
}

//////////////////////////////////////////////////////////////////////////////////////

task main()
{

	while(true)

	{
		drive();
		ctrl_intake();
		ctrl_shooter();

	}


}

//////////////////////////////////////////////////////////////////////////////////////////////////
