#pragma config(Sensor, in1,    arduino,        sensorAnalog)
#pragma config(Sensor, dgtl1,  encoder1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoder2,       sensorQuadEncoder)
#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           three,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           six,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           seven,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           eight,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           nine,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ten,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           five,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           four,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          two,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int arduinoValue;
int motorValue;

long map(long x, long in_min, long in_max, long out_min, long out_max);

task main()
{
	while(true)
	{
		if(vexRT[Btn5D] == 1)
		{
			motor[one] = 127;
			motor[two] = 127;
			motor[three] = 127;
			motor[four] = 127;
			motor[five] = 127;
			motor[six] = 127;
			motor[seven] = 127;
			motor[eight] = 127;
			motor[nine] = 127;
			motor[ten] = 127;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[one] = -127;
			motor[two] = -127;
			motor[three] = -127;
			motor[four] = -127;
			motor[five] = -127;
			motor[six] = -127;
			motor[seven] = -127;
			motor[eight] = -127;
			motor[nine] = -127;
			motor[ten] = -127;
		}
		else
		{
			motor[one] = 0;
			motor[two] = 0;
			motor[three] = 0;
			motor[four] = 0;
			motor[five] = 0;
			motor[six] = 0;
			motor[seven] = 0;
			motor[eight] = 0;
			motor[nine] = 0;
			motor[ten] = 0;
		}
		//writeDebugStreamLine("Encoder 1    : %d", SensorValue[encoder1]);
		//writeDebugStreamLine("Encoder 2    : %d", SensorValue[encoder2]);
		wait1Msec(200);

	}
}

long map(long x, long in_min, long in_max, long out_min, long out_max)
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
