#pragma config(Motor,  port2,           rightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           liftRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive();
void lift();
int DEAD = 10;

task main()
{
	while(true){
		drive();
		lift();
	}
}

void drive(){
	if(vexRT[Ch3] >= DEAD || vexRT[Ch3] <= -DEAD){
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];
	}
	else{
		motor[leftFront] = 0;
		motor[leftBack] = 0;
	}
	if(vexRT[Ch2] >= DEAD || vexRT[Ch2] <= -DEAD){
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
	}
	else{
		motor[rightFront] = 0;
		motor[rightBack] = 0;
	}
}

void lift() {
	if(vexRT[Btn5D] == 1){
		motor[liftLeft] = 120;
		motor[liftRight] = 120;
	}
	else if(vexRT[Btn6D] == 1){
		motor[liftLeft] = -120;
		motor[liftRight] = -120;
	}
	else{
		motor[liftLeft] = 0;
		motor[liftRight] = 0;
	}
}
