#pragma config(Motor,  port1,           leftBack,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive();

int DEADZONE = 10;

task main()
{
	while(true)
	{
		drive();
	}
}

void drive()
{
	int X1 = vexRT[Ch3];
	int X2 = vexRT[Ch2];
	if(abs(X1) < DEADZONE)
		X1 = 0;
	if(abs(X2) < DEADZONE)
		X2 = 0;
	motor[leftFront] = X1;
	motor[leftBack] = X1;
	motor[rightFront] = X2;
	motor[rightBack] = X2;
}
