#pragma config(Motor,  port2,           BkLeftSide,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FtLeftSide,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FtRightSide,   tmotorVex393, openLoop)
#pragma config(Motor,  port9,           BkRightSide,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int DEADZONE = 10;

void drive();

task main()
{
	while(true){
		drive();
	}
}

void drive(){
	if(vexRT[Ch3] >= DEADZONE || vexRT[Ch3] <= -DEADZONE){
		motor[FtLeftSide] = vexRT[Ch3];
		motor[BkLeftSide] = vexRT[Ch3];
	}
	else{
		motor[FtLeftSide] = 0;
		motor[BkLeftSide] = 0;
	}
	if(vexRT[Ch2] >= DEADZONE || vexRT[Ch2] <= -DEADZONE){
		motor[FtRightSide] = vexRT[Ch2];
		motor[BkRightSide] = vexRT[Ch2];
	}
	else{
		motor[FtRightSide] = 0;
		motor[BkRightSide] = 0;
	}
}
