#pragma config(Motor,  port1,           intakesack1,   tmotorVex269, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           lift1,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           intake1,       tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftSide,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightSide,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           intake2,       tmotorVex393, openLoop)
#pragma config(Motor,  port8,           lift2,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           right2,        tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intakesack2,   tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int DEADZONE = 15;

void drive();
void lift();
void intake();
void intakeSack();

task main()
{
	while(true){
		drive();
		lift();
		intake();
		intakeSack();
	}
}

void drive(){
	if(vexRT[Ch3] >= DEADZONE || vexRT[Ch3] <= -DEADZONE){
		motor[leftSide] = vexRT[Ch3];
		motor[left2] = vexRT[Ch3];
	}
	else{
		motor[leftSide] = 0;
		motor[left2] = 0;
	}
	if(vexRT[Ch2] >= DEADZONE || vexRT[Ch2] <= -DEADZONE){
		motor[rightSide] = vexRT[Ch2];
		motor[right2] = vexRT[Ch2];
	}
	else{
		motor[rightSide] = 0;
		motor[right2] = 0;
	}
}

void lift(){
	if(vexRT[Btn5U] == 1){
		motor[lift1] = 120;
		motor[lift2] = 120;
	}
	else if(vexRT[Btn5D] == 1){
			motor[lift1] = -120;
			motor[lift2] = -120;
	}
	else{
			motor[lift1] = 0;
			motor[lift2] = 0;
	}
}

void intake(){
	if(vexRT[Btn6U] == 1){
		motor[intake1] = 120;
		motor[intake2] = 120;
	}
	else if(vexRT[Btn6D] == 1){
			motor[intake1] = -120;
			motor[intake2] = -120;
	}
	else{
			motor[intake1] = 0;
			motor[intake2] = 0;
	}
}

void intakeSack(){
	if(vexRT[Btn8U] == 1){
		motor[intakesack1] = 120;
		motor[intakesack2] = 120;
	}
	else if(vexRT[Btn8D] == 1){
			motor[intakesack1] = -120;
			motor[intakesack2] = -120;
	}
	else{
			motor[intakesack1] = 0;
			motor[intakesack2] = 0;
	}
}
