#pragma config(Sensor, in1,    autoPot,        sensorPotentiometer)
#pragma config(Motor,  port1,           leftLiftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           testF,         tmotorVex269, openLoop)
#pragma config(Motor,  port5,           testB,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           chainMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightLiftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightEnd,      tmotorVex269, openLoop)
#pragma config(Motor,  port9,           backHand,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftEnd,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//motors

int DEADZONE = 10;
int SPEED = 127;
int mode;

void drive();
void lift();
void liftArm();

int chooseAutonomous();
long map(long x, long in_min, long in_max, long out_min, long out_max);

void pre_auton(){

}

task autonomous(){
		mode = chooseAutonomous();

		if(mode == 1){
			//drive forward
			motor[leftDrive] = 120;
			motor[rightDrive] = 110;
			wait10Msec(180);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			wait10Msec(100);
			//start lift
			liftArm();
			//Drive backward
			motor[leftDrive] = -120;
			motor[rightDrive] = -120;
			wait10Msec(100);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
		}
		else{

			motor[leftDrive] = 100;
			motor[rightDrive] = 90;
			wait10Msec(130);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			wait10Msec(55);
			motor[rightDrive] = -55;
			motor[leftDrive] = 55;
			wait10Msec(60);
			motor[rightDrive] = 0;
			motor[leftDrive] = 0;
			wait10Msec(50);
			motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(180);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			liftArm();
			motor[testF] = SPEED;
			motor[testB] = -SPEED;
			wait10Msec(100);
			motor[leftLiftMotor] = SPEED;
			motor[rightLiftMotor] = SPEED;
			wait10Msec(100);
			motor[leftLiftMotor] = 0;
			motor[rightLiftMotor] = 0;
			motor[chainMotor] = SPEED;
			wait10Msec(300);
			motor[chainMotor] = 0;
			motor[testB] = 0;
			motor[testF] = 0;

			/*motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(100);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			wait10Msec(50);
			motor[rightDrive] = -50;
			motor[leftDrive] = 55;
			wait10Msec(45);
			motor[rightDrive] = 0;
			motor[leftDrive] = 0;
			wait10Msec(50);
			motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(150);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			*/
		/*motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[leftLiftMotor] = 100;
		motor[rightLiftMotor] = 100;
		wait10Msec(30);
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		motor[chainMotor] = SPEED;
		wait10Msec(300);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[chainMotor] = SPEED;
		wait10Msec(200);
		motor[chainMotor] = 0;
		wait10Msec(25); //wait10Msec(50);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		motor[chainMotor] = SPEED;
		motor[leftLiftMotor] = -127;
		motor[rightLiftMotor] = -127;
		wait10Msec(50);
		motor[testB] = 0;
		motor[testF] = 0;
		motor[chainMotor] = 0;
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		wait10Msec(10);*/
		}
			/*
			bridge block w/o dc converter
			motor[leftDrive] = 100;
			motor[rightDrive] = 90;
			wait10Msec(130);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			wait10Msec(55);
			motor[rightDrive] = -55;
			motor[leftDrive] = 55;
			wait10Msec(60);
			motor[rightDrive] = 0;
			motor[leftDrive] = 0;
			wait10Msec(50);
			motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(180);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			liftArm();
			motor[testF] = SPEED;
			motor[testB] = -SPEED;
			wait10Msec(100);
			motor[leftLiftMotor] = SPEED;
			motor[rightLiftMotor] = SPEED;
			wait10Msec(100);
			motor[leftLiftMotor] = 0;
			motor[rightLiftMotor] = 0;
			motor[chainMotor] = SPEED;
			wait10Msec(300);
			motor[chainMotor] = 0;
			motor[testB] = 0;
			motor[testF] = 0;
			*/


			/*motor[rightDrive] = -25;
			wait10Msec(25);
			motor[rightDrive] = 100;
			wait10Msec(400);
			//start lift
			motor[testF] = SPEED;
			motor[testB] = -SPEED;
			wait10Msec(100);
			motor[leftLiftMotor] = 100;
			motor[rightLiftMotor] = 100;
			wait10Msec(100);
			motor[leftLiftMotor] = 0;
			motor[rightLiftMotor] = 0;
			motor[chainMotor] = 120;
			wait10Msec(300);
			motor[testF] = SPEED;
			motor[testB] = -SPEED;
			wait10Msec(100);
			motor[chainMotor] = SPEED;
			wait10Msec(200);
			motor[chainMotor] = 0;
			wait10Msec(25); //wait10Msec(50);
			motor[testF] = SPEED;
			motor[testB] = -SPEED;
			motor[chainMotor] = SPEED;
			motor[leftLiftMotor] = -127;
			motor[rightLiftMotor] = -127;
			wait10Msec(50);
			motor[testB] = 0;
			motor[testF] = 0;
			motor[chainMotor] = 0;
			motor[leftLiftMotor] = 0;
			motor[rightLiftMotor] = 0;
			//Drive backward
			motor[leftDrive] = -120;
			motor[rightDrive] = -120;
			wait10Msec(100);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
		}*/
		while(true){}
		/*motor[leftDrive] = 100;
		motor[rightDrive] = 100;
		motor[leftLiftMotor] = 127;
		motor[rightLiftMotor] = 127;
		motor[testF] = 127;
		motor[testB] = -127;
		wait10Msec(25);
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		motor[chainMotor] = 127/6;
		wait10Msec(175);
		//motor[rightDrive] = -100;
		//motor[leftDrive] = -100;
		//wait10Msec(100);
		motor[rightDrive] = -100;
		motor[leftDrive] = -100;
		wait10Msec(100);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
		motor[testF] = 0;
		motor[testB] = 0;
		motor[chainMotor] = 0;
		*/
		/*motor[leftDrive] = 100;
		motor[rightDrive] = 100;
		wait10Msec(200);
		motor[leftDrive] = -100;
		motor[rightDrive]= -100;
		wait10Msec(100);
		motor[leftDrive] = 0;
		motor[rightDrive] = 0;
		*/

			//driving with DC converter
			motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(100);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			wait10Msec(50);
			motor[rightDrive] = -50;
			motor[leftDrive] = 55;
			wait10Msec(45);
			motor[rightDrive] = 0;
			motor[leftDrive] = 0;
			wait10Msec(50);
			motor[leftDrive] = 100;
			motor[rightDrive] = 95;
			wait10Msec(150);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			liftArm();


		//drive forward
		motor[leftDrive] = 120;
		motor[rightDrive] = 120;
		wait10Msec(200);
		motor[leftDrive] = 0;
		motor[rightDrive] = 0;
		wait10Msec(100);
		//start lift
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[leftLiftMotor] = 100;
		motor[rightLiftMotor] = 100;
		wait10Msec(100);
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		motor[chainMotor] = 120;
		wait10Msec(300);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[chainMotor] = SPEED;
		wait10Msec(200);
		motor[chainMotor] = 0;
		wait10Msec(25); //wait10Msec(50);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		motor[chainMotor] = SPEED;
		motor[leftLiftMotor] = -127;
		motor[rightLiftMotor] = -127;
		wait10Msec(50);
		motor[testB] = 0;
		motor[testF] = 0;
		motor[chainMotor] = 0;
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		//Drive backward
		motor[leftDrive] = -120;
		motor[rightDrive] = -120;
		wait10Msec(100);
		motor[leftDrive] = 0;
		motor[rightDrive] = 0;
}

task usercontrol(){
	while (true){
		mode = chooseAutonomous();
 	   drive();
	   lift();
	}
}
void drive(){
	if(vexRT[Ch3] > DEADZONE || vexRT[Ch3] < -DEADZONE){
		motor[leftDrive]=vexRT[Ch3];
	}
	else{
		motor[leftDrive]=0;
	}
	if(vexRT[Ch2] > DEADZONE || vexRT[Ch2] < -DEADZONE){
		motor[rightDrive]=vexRT[Ch2];
	}
	else{
		motor[rightDrive]=0;
	}
}
void lift(){
	if(vexRT[Btn6U]==1){
		motor[chainMotor]=SPEED;
	}
	else if(vexRT[Btn6D]==1){
		motor[chainMotor]=-SPEED;
	}
	else{
		motor[chainMotor]=0;
	}
	if(vexRT[Btn5U]==1){
		motor[testF]=SPEED;
		motor[testB]=-SPEED;
	}
	else if(vexRT[Btn5D]==1){
		motor[testF]=-SPEED;
		motor[testB]=SPEED;
	}
	else{
		motor[testF]=0;
		motor[testB]=0;
	}
	if(vexRT[Btn8U]==1){
		motor[leftLiftMotor]=SPEED;
		motor[rightLiftMotor]=SPEED;
	}
	else if(vexRT[Btn8D]==1){
		motor[leftLiftMotor]=-SPEED;
		motor[rightLiftMotor]=-SPEED;
	}
	else{
		motor[leftLiftMotor]=0;
		motor[rightLiftMotor]=0;
	}
	if(vexRT[Btn8R]==1){
		motor[rightEnd]=SPEED;
		motor[leftEnd]=SPEED;
	}
	else if(vexRT[Btn8L]==1){
		motor[rightEnd]=-SPEED;
		motor[leftEnd]=-SPEED;
	}
	else{
		motor[rightEnd]=0;
		motor[leftEnd]=0;
	}
}
void liftArm(){
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[leftLiftMotor] = 100;
		motor[rightLiftMotor] = 100;
		wait10Msec(100);
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		motor[chainMotor] = 120;
		wait10Msec(300);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		wait10Msec(100);
		motor[chainMotor] = SPEED;
		wait10Msec(200);
		motor[chainMotor] = 0;
		wait10Msec(25); //wait10Msec(50);
		motor[testF] = SPEED;
		motor[testB] = -SPEED;
		motor[chainMotor] = SPEED;
		motor[leftLiftMotor] = -127;
		motor[rightLiftMotor] = -127;
		wait10Msec(50);
		motor[testB] = 0;
		motor[testF] = 0;
		motor[chainMotor] = 0;
		motor[leftLiftMotor] = 0;
		motor[rightLiftMotor] = 0;
		wait10Msec(10);
}

// Generates a number from 1 to 4 based on potentiometer value
int chooseAutonomous(){
  return map(SensorValue[autoPot], 0, 4000, 1, 4);
}

long map(long x, long in_min, long in_max, long out_min, long out_max)
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
