#pragma config(Motor,  port6,           liftRight2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           liftLeft1,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           liftRight1,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void drive();
void lift();
//void endEffector();

void liftMotors(int speed){
	motor[liftRight1] = speed;
	motor[liftLeft1] = speed;
	motor[liftLeft2] = speed;
	motor[liftRight2] = speed;
}

task main()
{
	while(true){
		//drive();
		lift();
		//endEffector();
	}
}
//User Functions
void lift(){
	if (vexRT[Btn6U] == 1){
		liftMotors(127);
	}
	else if (vexRT[Btn6D] == 1){
		liftMotors(-127);
	}
	else liftMotors(0);
}
