#pragma config(Sensor, dgtl1,  touchL,         sensorTouch)
#pragma config(Sensor, dgtl2,  touchR,         sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           liftLeftU,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           liftLeftD,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftRightU,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftRightD,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intakeRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(60)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void tank();
void lift();
void intake();


#define deadZone 10
#define speed 120


void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}


task usercontrol()
{
	while (true)
	{
	  tank();
	  lift();
	  intake();
	}
}

void tank()
{
	int Y1 = vexRT[Ch3];
	int Y2 = vexRT[Ch2];
	if(abs(Y1) < deadZone)
	{
		Y1 = 0;
	}
	if(abs(Y2) < deadZone)
	{
		Y2 = 0;
	}
	motor[leftFront] = Y1;
	motor[leftBack] = Y1;
	motor[rightFront] = Y2;
	motor[rightBack] = Y2;
}

void lift()
{
	int liftUp = vexRT[Btn5U];
	int liftDown = vexRT[Btn5D];
	int liftSpeed;
	bool liftStop = true;
	while ((SensorValue[touchR] == 1) && (SensorValue[touchL] == 1))
	{
		liftStop = false;
	}
	if(liftUp == 1)
	{
		liftSpeed = speed;
	}
	else if(liftDown == 1 && liftStop)
	{
		liftSpeed = -speed;
	}
	else
	{
		liftSpeed = 0;
	}

	motor[liftLeftU] = liftSpeed;
	motor[liftLeftD] = liftSpeed;
	motor[liftRightU] = liftSpeed;
	motor[liftRightD] = liftSpeed;
}

void intake()
{
	int motorpower = (vexRT[Btn6U] == 1) ? -100 : (vexRT[Btn6D] == 1) ? 100 : 0;
	motor[intakeLeft] = motorpower;
	motor[intakeRight] = motorpower;
}
