//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Arduino to Cortex UART bridge code

	Idea is to use the UART port on the Cortex to transmit data from external
	sensors on the Arduino to the Cortex. Must be parsed.




*/
task UARTReceive();
int nRcvIndex = 0;
long nTotalRcvChars = 0;
long nTotalXmitChars = 0;
long nTotalRcvOutOfSequence = 0;

int rcvChar;
unsigned char rcvChars[23]; // Keep buffer of last 23 characters received.




task main()
{
	bLCDBacklight = true;
 	configureSerialPort(UART1, uartUserControl); //Configure Port Two For UART manually
 	setBaudRate(UART1, baudRate115200);

 	while (getChar(UART1) != -1) // Purge existing chars from buffer
  {}

  startTask(UARTReceive);
	while(true)
	{}

}

task UARTReceive()
{
 while (true)
 {
 // Loop forever getting characters from the "receive" UART. Validate that they arrive in the expected
 // sequence.

 static int nLastRcvChar = 0;

 rcvChar = getChar(UART1);
 if (rcvChar == -1)
 {
 // No character available

 wait1Msec(3); // Don't want to consume too much CPU time. Waiting eliminates CPU consumption for this task.
 continue;
 }
 ++nLastRcvChar;
 nLastRcvChar %= 256;
 if (nLastRcvChar != rcvChar)
 ++nTotalRcvOutOfSequence;



 nLastRcvChar = rcvChar;
 rcvChars[nRcvIndex] = rcvChar;
 ++nTotalRcvChars;
 ++nRcvIndex;
 if (nRcvIndex >= sizeof(rcvChars))
 nRcvIndex = 0;
 }
}
