#pragma config(Sensor, dgtl1,  liftRightEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  liftLeftEnc,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           liftLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           wristMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           intakeMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive();
void lift();
void inTake();
void checkLiftSpeed();

void rotation();

#define deadZone 25
#define speed 120
int liftSpeedRight,liftSpeedLeft;

task main(){
	while(true){
		drive();
		lift();
		inTake();
		rotation();
	}
}

void drive(){
	int Y1 = vexRT[Ch3];
	int X2 = vexRT[Ch1];
	int X1 = vexRT[Ch4];
	if(abs(Y1) < deadZone)
		Y1 = 0;
	if(abs(X2) < deadZone)
		X2 = 0;
	if(abs(X1) < deadZone)
		X1 = 0;
	motor[leftFront] = Y1 + X2 + X1;
	motor[leftBack] = Y1 + X2 - X1;
	motor[rightFront] = Y1 - X2 - X1;
	motor[rightBack] = Y1 - X2 + X1;
}

void lift(){
	int liftDown = vexRT[Btn6D];
	int liftUp = vexRT[Btn6U];
	int liftSpeedRight,liftSpeedLeft;
	if(liftUp == 1){
		liftSpeedRight = speed;
		liftSpeedLeft = speed;
	}
	else if(liftDown == 1){
		liftSpeedRight = -speed;
		liftSpeedLeft = -speed;
	}
	else{
		liftSpeedRight = 0;
		liftSpeedLeft = 0;
	}
	if(liftSpeedRight != 0 && liftSpeedLeft != 0)
			checkLiftSpeed();
	motor[liftLeft] = liftSpeedLeft;
	motor[liftRight] = liftSpeedRight;
}

//checks Encoder values to regulate the speed of lift | 36
void checkLiftSpeed(){
	//lift is going up
	if(liftSpeedRight > 0 && liftSpeedLeft > 0){
		if(SensorValue[liftRightEnc] > SensorValue[liftLeftEnc])
			liftSpeedRight -= 10;
		else if(SensorValue[liftLeftEnc] > SensorValue[liftRightEnc])
			liftSpeedLeft -= 10;
	}
	//lift is going down
	else if(liftSpeedRight < 0 && liftSpeedLeft < 0){
		if(SensorValue[liftRightEnc] > SensorValue[liftLeftEnc])
			liftSpeedLeft -= 10;
		else if(SensorValue[liftLeftEnc] > SensorValue[liftRightEnc])
			liftSpeedRight -= 10;
	}
}

void inTake(){
	int inTake = vexRT[Btn5U];
	int outTake = vexRT[Btn5D];
	int takeSpeed;
	if(inTake == 1)
		takeSpeed = speed;
	else if(outTake == 1)
		takeSpeed = -speed;
	else
		takeSpeed = 0;
	motor[intakeMotor] = takeSpeed;
}

void rotation(){
	//int rotaSpeed = vexRT[Ch2];
	int rotaUp = vexRT[Btn8U];
	int rotaDown = vexRT[Btn8D];
	int rotaSpeed;
	if(abs(rotaSpeed) < deadZone)
		rotaSpeed = 0;
	if(rotaUp == 1)
		rotaSpeed = speed;
	else if(rotaDown == 1)
		rotaSpeed = -speed;
	else
		rotaSpeed = 0;
	motor[wristMotor] = rotaSpeed;
}
