#pragma config(Motor,  port2,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           endMotor1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           endMotor2,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void endEffector();
void manipulator();
void shooter();

int wheelSpeed;

task main()
{
	while(true)
	{
		//endEffector();
		shooter();
		manipulator();
	}
}

//void endEffector()
//{
//	if(vexRT[Btn8U]==1 && wheelSpeed<120 && wheelSpeed!=120)
//	{
//			wheelSpeed=wheelSpeed+10;
//			motor[leftMotor1] = wheelSpeed;
//			motor[leftMotor2] = wheelSpeed;
//			motor[rightMotor1] = wheelSpeed;
//			motor[rightMotor2] = wheelSpeed;
//	}
//	else if(vexRT[Btn8D]==1 && wheelSpeed>=10)
//	{
//			wheelSpeed=wheelSpeed-10;
//			motor[leftMotor1] = wheelSpeed;
//			motor[leftMotor2] = wheelSpeed;
//			motor[rightMotor1] = wheelSpeed;
//			motor[rightMotor2] = wheelSpeed;
//	}
//	if(vexRT[Btn6U] == 1)
//	{
//		motor[leftMotor1] = wheelSpeed;
//		motor[leftMotor2] = wheelSpeed;
//		motor[rightMotor1] = wheelSpeed;
//		motor[rightMotor2] = wheelSpeed;
//	}
//	else if(vexRT[Btn6D] == 1)
//	{
//			motor[leftMotor1] = 0;
//			motor[leftMotor2] = 0;
//			motor[rightMotor1] = 0;
//			motor[rightMotor2] = 0;
//	}
//}

void shooter()
{
	if(vexRT[Btn8U] == 1)
		wheelSpeed = 120;
	else if(vexRT[Btn8R] == 1)
		wheelSpeed = 100;
	else if(vexRT[Btn8D] == 1)
		wheelSpeed = 80;
	else if(vexRT[Btn8L] == 1)
		wheelSpeed = 60;
	if(vexRT[Btn6U] == 1)
	{
		motor[leftMotor1] = wheelSpeed;
		motor[leftMotor2] = wheelSpeed;
		motor[rightMotor1] = wheelSpeed;
		motor[rightMotor2] = wheelSpeed;
	}
	else if(vexRT[Btn6D] == 1)
	{
			motor[leftMotor1] = 0;
			motor[leftMotor2] = 0;
			motor[rightMotor1] = 0;
			motor[rightMotor2] = 0;
	}
}

void manipulator()
{
	if(vexRT[Btn5U]==1)
	{
		motor[endMotor1] = 120;
		motor[endMotor2] = 120;
	}
	if(vexRT[Btn5D]==1)
	{
		motor[endMotor1] = 0;
		motor[endMotor2] = 0;
	}
}
