#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void motorTest();

task main()
{
	while(true)
		{

		motorTest();

		}
}


void motorTest()
{
	int motorSpeed = vexRT[Ch3];
	if( (SensorValue[button]==0)
				&&((motorSpeed>10) || (motorSpeed<-10))
)
	{
		motor[leftDrive]=motorSpeed;
		motor[rightDrive]=motorSpeed;
	}

	else if( SensorValue[button]==1 )
	{
		motor[leftDrive]=0;
		motor[rightDrive]=0;
		wait1Msec(1500);
	}
	wait1Msec(500);









}
