#pragma config(Sensor, dgtl2,  Solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           wheelMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           wheelMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           wheelMotor2,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pneumatics();

task main()
{
	while(true)
		pneumatics();
}


void pneumatics()
{
if(vexRT[Btn6U]==1)
	SensorValue(Solenoid)=1;
else if(vexRT[Btn6D]==1)
	SensorValue(Solenoid)=0;
if(vexRT[Btn8U]==1)
	{
	motor[wheelMotor]=120;
	motor[wheelMotor1]=120;
	motor[wheelMotor2]=120;
	}
	else if(vexRT[Btn8L]==1)
	{
	motor[wheelMotor]=60;
	motor[wheelMotor1]=60;
	motor[wheelMotor2]=60;
	}
	else if(vexRT[Btn8D]==1)
	{
	motor[wheelMotor]=0;
	motor[wheelMotor1]=0;
	motor[wheelMotor2]=0;
	}
}
