#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftSolenoid,   sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rightSolenoid,  sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDrive1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftShooter,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           leftIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightShooter,  tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           rightDrive2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive();
void intake();
void shooter();
int deadzone;
int wheelSpeed;

task main()
{
	while(true)
	{
		drive();
		intake();
		shooter();
	}
}


void drive()
{
	deadzone=10;

	if(vexRT[Ch3]>deadzone || vexRT[Ch3]<-deadzone)
	{
		motor[leftDrive]=vexRT[Ch3];
		motor[leftDrive1]=vexRT[Ch3];
		motor[leftDrive2]=vexRT[Ch3];
	}
	else
	{
		motor[leftDrive]=0;
		motor[leftDrive1]=0;
		motor[leftDrive2]=0;
	}
	if(vexRT[Ch2]>deadzone || vexRT[Ch2]<-deadzone)
	{
		motor[rightDrive]=vexRT[Ch2];
		motor[rightDrive1]=vexRT[Ch2];
		motor[rightDrive2]=vexRT[Ch2];
	}
	else
	{
		motor[rightDrive]=0;
		motor[rightDrive1]=0;
		motor[rightDrive2]=0;
	}
}

void shooter()
{

	if(vexRT[Btn8U] == 1)
		wheelSpeed = 80;
	else if(vexRT[Btn8R] == 1)
		wheelSpeed = 70;
	else if(vexRT[Btn8D] == 1)
		wheelSpeed = 55;
	else if(vexRT[Btn8L] == 1)
		wheelSpeed = 50;
	if(vexRT[Btn6U] == 1)
	{
		motor[leftShooter] = wheelSpeed;
		motor[rightShooter] = wheelSpeed;
	}
	else if(vexRT[Btn6D] == 1)
	{
		motor[leftShooter] = 0;
		motor[rightShooter] = 0;
	}
}

void intake()
{
	if(vexRT[Btn5U]==1)
	{
		motor[leftIntake] = 120;
		motor[rightIntake] = 120;
	}
	if(vexRT[Btn5D]==1)
	{
		motor[leftIntake] = 0;
		motor[rightIntake] = 0;
  }
	//else if (vexRT[Btn5U]!=1 && vexRT[Btn5D]!=1)
	//{
	//	motor[leftIntake] = 0;
	//	motor[rightIntake] = 0;
	//}

}
